contacts/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('industry/', create_industry, name='industry'),
    path('industry/update/<int:pk>', update_industry, name='update-industry'),
    path('industry/delete/<int:pk>', delete_industry, name='delete-industry'),
    path('country/', home_countries, name='country'),
    path('country/update/<int:pk>', update_country, name='update-country'),
    path('country/delete/<int:pk>', delete_country, name='delete-country'),
    path('cities/', home_cities, name='cities'),
    path('cities/update/<int:pk>', update_cities, name='update-cities'),
    path('cities/delete/<int:pk>', delete_cities, name='delete-cities'),
    path('employees/', home_employees, name='employees'),
    path('customers/', home_customers, name='customers'),
    path('customers/new/', create_customers, name='create-customers'),
    path('customers/update/<int:pk>', update_customers, name='update-customers'),
    path('customers/delete/<int:pk>', delete_customers, name='delete-customers'),
    path('customers/export_csv/', export_customers, name='export-customers'),
    path('suppliers/', home_suppliers, name='suppliers'),
]

erpLite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('login.urls'), name='login'),
    path('', include('home.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name="home"),
]

contacts/models.py
from django.db import models


# Global Information(Abstraction field)
class GlobalInformation(models.Model):
    GENDER = [
        ('', '----'),
        ('F', 'Female'),
        ('M', 'Male'),
    ]
    first_name = models.CharField(max_length=220, default='')
    last_name = models.CharField(max_length=220, default='')
    email = models.EmailField(max_length=220, default='')
    phone_number = models.CharField(max_length=20, blank=True, default='')
    mobil_number = models.CharField(max_length=20, blank=True, default='')
    address = models.CharField(max_length=250, blank=True, default='')
    postcode = models.CharField(max_length=50, blank=True, default='')
    company_name = models.CharField(max_length=220, default='')
    job_title = models.CharField(max_length=20, blank=True, default='')
    gender = models.CharField(max_length=20, choices=GENDER, default='')

    class Meta:
        abstract = True


# Customers
class Customers(GlobalInformation):
    tax_id = models.CharField(max_length=20, blank=True, default='')


# Suppliers
class Suppliers(GlobalInformation):
    website = models.URLField(max_length=220, blank=True, default='')


# Employees
class Employees(GlobalInformation):
    birthday = models.DateField(blank=True, null=True, default='')


# Industries
class Industries(models.Model):
    name = models.CharField(max_length=220)
    description = models.CharField(max_length=220)

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        self.description = self.description.upper()
        return super(Industries,self).save(*args, **kwargs)


# Countries
class Countries(models.Model):
    name = models.CharField(max_length=220)
    code = models.CharField(max_length=5)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        self.code = self.code.upper()
        return super(Countries, self).save(*args, **kwargs)


# Cities
class Cities(models.Model):
    name = models.CharField(max_length=220)
    country_id = models.ForeignKey(Countries, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        return super(Cities, self).save(*args, **kwargs)

contacts/forms.py
from django.forms import ModelForm, TextInput, Select, EmailInput
from .models import Industries, Countries, Cities, Customers


class FormIndustry(ModelForm):
    class Meta:
        model = Industries
        fields = '__all__'


class FormCountry(ModelForm):
    class Meta:
        model = Countries
        fields = '__all__'


class FormCities(ModelForm):
    class Meta:
        model = Cities
        fields = '__all__'

customers_field = "form-control"

class FormCustomers(ModelForm):
    class Meta:
        model = Customers
        fields = '__all__'
        widgets = {
            'first_name': TextInput(attrs={"class":f"{customers_field}"}),
            'last_name': TextInput(attrs={"class":f"{customers_field}"}),
            'job_title': TextInput(attrs={"class":f"{customers_field}"}),
            'gender': Select(attrs={"class":f"{customers_field}"}),
            'phone_number': TextInput(attrs={"class":f"{customers_field}"}),
            'mobil_number': TextInput(attrs={"class":f"{customers_field}"}),
            'email': EmailInput(attrs={"class":f"{customers_field}"}),
            'company_name': TextInput(attrs={"class":f"{customers_field}"}),
            'address': TextInput(attrs={"class":f"{customers_field}"}),
            'postcode': TextInput(attrs={"class":f"{customers_field}"}),
            'tax_id': TextInput(attrs={"class":f"{customers_field}"}),
        }

contacts/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Industries, Countries, Cities, Customers
from .forms import FormIndustry, FormCountry, FormCities, FormCustomers
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import csv

# Countries
@login_required(login_url='login')
def home_countries(request):
    form = FormCountry()
    if request.method == 'POST':
        form = FormCountry(request.POST)
        if form.is_valid():
            form.save()
        return redirect('contacts:country')
    countries_list = Countries.objects.all()
    paginator = Paginator(Countries.objects.all(), 6)
    page_number = request.GET.get('page')
    page_country = paginator.get_page(page_number)
    context = {
        'form': form,
        'countries_list': countries_list,
        'page_country': page_country,
    }
    return render(request, 'countries.html', context)

@login_required(login_url='login')
def update_country(request, pk):
    country = Countries.objects.get(id=pk)
    if request.method == 'POST':
        form = FormCountry(request.POST, instance=country)
        if form.is_valid():
            form.save()
        return redirect('contacts:country')
    else:
        form = FormCountry(instance=country)
    page_country = Countries.objects.all()
    page_name = request.path
    context = {
        'form': form,
        'page_country': page_country,
        'page_name': page_name,
    }
    return render(request, 'countries.html', context)

@login_required(login_url='login')
def delete_country(request, pk):
    country = Countries.objects.get(id=pk)
    country.delete()
    return redirect('contacts:country')


# Industries
@login_required(login_url='login')
def create_industry(request):
    form = FormIndustry()
    if request.method == 'POST':
        form = FormIndustry(request.POST)
        if form.is_valid():
            form.save()
        return redirect('contacts:industry')
    industries_list = Industries.objects.all()
    paginator = Paginator(Industries.objects.all(), 6)
    page_number = request.GET.get('page')
    page_industry = paginator.get_page(page_number)
    context = {
        'form': form,
        'industries_list': industries_list,
        'page_industry': page_industry,
    }
    return render(request, 'industries.html', context)

@login_required(login_url='login')
def update_industry(request, pk):
    industry = Industries.objects.get(id=pk)
    if request.method == 'POST':
        form = FormIndustry(request.POST, instance=industry)
        if form.is_valid():
            form.save()
        return redirect('contacts:industry')
    else:
        form = FormIndustry(instance=industry)
    page_industry = Industries.objects.all()
    page_name = request.path
    context = {
        'form': form,
        'page_industry': page_industry,
        'page_name': page_name,
    }
    return render(request,'industries.html', context)

@login_required(login_url='login')
def delete_industry(request, pk):
    industry = Industries.objects.get(id=pk)
    industry.delete()
    return redirect('contacts:industry')


# Countries
@login_required(login_url='login')
def home_cities(request):
    form = FormCities()
    if request.method == 'POST':
        form = FormCities(request.POST)
        if form.is_valid():
            form.save()
        return redirect('contacts:cities')
    cities_list = Cities.objects.all()
    paginator = Paginator(Cities.objects.all(), 6)
    page_number = request.GET.get('page')
    page_city = paginator.get_page(page_number)
    context = {
        'form': form,
        'cities_list': cities_list,
        'page_city': page_city,
    }
    return render(request, 'cities.html', context)

@login_required(login_url='login')
def update_cities(request, pk):
    city = Cities.objects.get(id=pk)
    if request.method == 'POST':
        form = FormCities(request.POST, instance=city)
        if form.is_valid():
            form.save()
        return redirect('contacts:cities')
    else:
        form = FormCities(instance=city)
    page_city = Cities.objects.all()
    page_name = request.path
    context = {
        'form': form,
        'page_city': page_city,
        'page_name': page_name,
    }
    return render(request, 'cities.html', context)

@login_required(login_url='login')
def delete_cities(request, pk):
    city = Cities.objects.get(id=pk)
    city.delete()
    return redirect('contacts:cities')


@login_required(login_url='login')
def home_employees(request):
    return render(request, 'employees.html')


@login_required(login_url='login')
def home_customers(request):
    customers = Customers.objects.all()
    paginator = Paginator(Customers.objects.all(), 6)
    page_number = request.GET.get('page')
    page_customers = paginator.get_page(page_number)
    context = {
        'customers': customers,
        'page_customers': page_customers,
    }
    return render(request, 'customers.html', context)


@login_required(login_url='login')
def create_customers(request):
    print(request.POST)
    form = FormCustomers()
    if request.method == 'POST':
        form = FormCustomers(request.POST)
        if form.is_valid():
            form.save()
        return redirect('contacts:customers')
    context = {
        'form': form,
    }
    return render(request, 'customerForm.html', context)


@login_required(login_url='login')
def update_customers(request, pk):
    customers = Customers.objects.get(id=pk)
    if request.method == 'POST':
        form = FormCustomers(request.POST, instance=customers)
        if form.is_valid():
            form.save()
        return redirect('contacts:customers')
    else:
        form = FormCustomers(instance=customers)
    context = {
        'form': form
    }
    return render(request, 'customerForm.html', context)


@login_required(login_url='login')
def delete_customers(request, pk):
    customers = Customers.objects.get(id=pk)
    customers.delete()
    return redirect('contacts:customers')


# Customers Export
@login_required(login_url='login')
def export_customers(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=customers.csv'
    writer = csv.writer(response)
    customers = Customers.objects.all()
    writer.writerow(['ID', 'FUll Name', 'Phone', 'Email', 'Job Title', 'Company Name'])
    for customer in customers:
        writer.writerow([customer.id, (customer.first_name + ' ' + customer.last_name), customer.phone_number, customer.email, customer.job_title, customer.company_name])
    return response


@login_required(login_url='login')
def home_suppliers(request):
    return render(request, 'suppliers.html')

contacts/templates/cities.html
{% extends 'home.html' %}
{% block title %}
    Cities
{% endblock %}
{% block content %}
    <div class="row py-4">
        <div class="d-flex justify-content-between">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
{#                {% if request.method == 'POST' %}#}
                {% if page_name %}
                    <input type="submit" value="update" class="ms-2 btn btn-warning btn-sm">
                    <a href="{% url 'contacts:cities' %}" class="btn btn-secondary btn-sm">cancel</a>
                {% else %}
                    <input type="submit" value="create" class="ms-2 btn btn-erp-primary btn-sm">
                {% endif %}
            </form>
            <div class="px-4">
                {% for city in cities.number %}
                    {{ city }}
                {% endfor %}

                {{ page_city.number }}-{{ page_city.paginator.num_pages }}
                {% if page_city.has_previous %}
                    <a href="?page={{ page_city.previous_page_number }}"><i class="bi bi-caret-left-square-fill"></i></a>
                {% endif %}
                {% if page_city.has_next %}
                    <a href="?page={{ page_city.next_page_number }}"><i class="bi bi-caret-right-square-fill"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row bg-white p-4">
        <table class="table">
            <thead class="table-light">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% if page_city %}
                {% for city in page_city %}
                    <tr>
                        <td>{{ city.id }}</td>
                        <td>{{ city.name }}</td>
                        <td>{{ city.country_id.name}}</td>
                        <td><a href="{% url 'contacts:update-cities' city.pk %}" class="btn btn-warning btn-sm"><i
                                class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'contacts:delete-cities' city.pk %}" class="btn btn-danger btn-sm"><i
                                    class="bi bi-trash3"></i></a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>
                        No found data.
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>

    </div>
{% endblock %}

contacts/templates/countries.html
{% extends 'home.html' %}
{% block title %}
    Countries
{% endblock %}
{% block content %}
    <div class="row py-4">
        <div class="d-flex justify-content-between">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
{#                {% if request.method == 'POST' %}#}
                {% if page_name %}
                    <input type="submit" value="update" class="ms-2 btn btn-warning btn-sm">
                    <a href="{% url 'contacts:country' %}" class="btn btn-secondary btn-sm">cancel</a>
                {% else %}
                    <input type="submit" value="create" class="ms-2 btn btn-erp-primary btn-sm">
                {% endif %}
            </form>
            <div class="px-4">
                {% for country in countries.number %}
                    {{ country }}
                {% endfor %}

                {{ page_country.number }}-{{ page_country.paginator.num_pages }}
                {% if page_country.has_previous %}
                    <a href="?page={{ page_country.previous_page_number }}"><i class="bi bi-caret-left-square-fill"></i></a>
                {% endif %}
                {% if page_country.has_next %}
                    <a href="?page={{ page_country.next_page_number }}"><i class="bi bi-caret-right-square-fill"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row p-4">
        <table class="table">
            <thead class="table-light">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% if page_country %}
                {% for country in page_country %}
                    <tr>
                        <td>{{ country.id }}</td>
                        <td>{{ country.name }}</td>
                        <td>{{ country.code }}</td>
                        <td><a href="{% url 'contacts:update-country' country.pk %}" class="btn btn-warning btn-sm"><i
                                class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'contacts:delete-country' country.pk %}" class="btn btn-danger btn-sm"><i
                                    class="bi bi-trash3"></i></a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>
                        No found data.
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>

    </div>
{% endblock %}

contacts/templates/customerForm.html
{% extends 'home/home.html' %}

{% block Title %}
    Add Customers
{% endblock %}
{% block content %}
    <div class="row pt-2">
        <div class="col-8 mx-auto shadow-sm p-4 mb-5 bg-body">
            <form method="POST">
                {% csrf_token %}
                <div class="border-bottom mb-2">
                    <h5>Basic Information</h5>
                </div>
                <div class="row">
                    <div class="mb-3 col-6">
                        <label for="firstName" class="form-label">First Name</label>
                        {{ form.first_name }}
                    </div>
                    <div class="mb-3 col-6">
                        <label for="LastName" class="form-label">Last Name</label>
                        {{ form.last_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="mb-3 col-6">
                        <label for="jobTitle" class="form-label">Job Title</label>
                        {{ form.job_title }}
                    </div>
                    <div class="mb-3 col-6">
                        <label for="gender" class="form-label">Gender</label>
                        {{ form.gender }}
                    </div>
                </div>
                <div class="border-bottom mb-2 mt-4">
                    <h6>Contact Information</h6>
                </div>
                <div class="row">
                    <div class="mb-3 col-6">
                        <label for="phoneNumber" class="form-label">Phone Number</label>
                        {{ form.phone_number }}
                    </div>
                    <div class="mb-3 col-6">
                        <label for="mobilNumber" class="form-label">Mobil Number</label>
                        {{ form.mobil_number }}
                    </div>
                </div>
                <div class="row">
                    <div class="mb-3 col-6">
                        <label for="email" class="form-label">Email</label>
                        {{ form.email }}
                    </div>
                    <div class="mb-3 col-6">
                        <label for="companyName" class="form-label">Company Name</label>
                        {{ form.company_name }}
                    </div>
                </div>
                <div class="row">
                    <div class="mb-3 col-6">
                        <label for="adrress" class="form-label">Address</label>
                        {{ form.address }}
                    </div>
                    <div class="mb-3 col-2">
                        <label for="postCode" class="form-label">Post Code</label>
                        {{ form.postcode }}
                    </div>
                    <div class="mb-3 col-4">
                        <label for="taxID" class="form-label">Tax ID</label>
                        {{ form.tax_id }}
                    </div>
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="" class="btn btn-secondary btn-sm">Cancel</a>
                    <input type="submit" value="save" class="btn btn-primary btn-sm px-3">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

contacts/templates/customers.html
{% extends 'home.html' %}
{% block title %}
    Customers
{% endblock %}
{% block content %}
    <div class="row py-4">
        <div class="d-flex justify-content-between">
            <a href="{% url 'contacts:create-customers' %}" class="ms-2 btn btn-erp-primary btn-sm">Add Customer</a>
        <div>
                <a class="btn btn-erp-primary btn-sm " href="{% url 'contacts:export-customers' %}"><i
                        class="bi bi-save"></i><span class="ps-2">Export CSV</span></a>
            </div>
            <div class="px-4">
                {{ page_customers.number }}-{{ page_customers.paginator.num_pages }}
                {% if page_customers.has_previous %}
                    <a href="?page={{ page_customers.previous_page_number }}"><i
                            class="bi bi-caret-left-square-fill"></i></a>
                {% endif %}
                {% if page_customers.has_next %}
                    <a href="?page={{ page_customers.next_page_number }}"><i class="bi bi-caret-right-square-fill"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row bg-white p-4">
        <table class="table">
            <thead class="table-light">
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Job Title</th>
                <th>Company Name</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% if customers %}
                {% for client in customers %}
                    <tr>
                        <td>{{ client.id }}</td>
                        <td>{{ client.first_name }} {{ client.last_name }}</td>
                        <td>{{ client.mobil_number }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ client.job_title }}</td>
                        <td>{{ client.company_name }}</td>
                        <td><a href="{% url 'contacts:update-customers' client.pk %}" class="btn btn-warning btn-sm"><i
                                class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'contacts:delete-customers' client.pk %}" class="btn btn-danger btn-sm"><i
                                    class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>
                        No found data.
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>

    </div>
{% endblock %}

contacts/templates/employees.html
{% extends 'home.html' %}
{% block title %}
    Employees
{% endblock %}

contacts/templates/industries.html
{% extends 'home.html' %}
{% block title %}
    Industries
{% endblock %}
{% block content %}
    <div class="row py-4">
        <div class="d-flex justify-content-between">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
{#                {% if request.method == 'POST' %}#}
                {% if page_name %}
                    <input type="submit" value="update" class="ms-2 btn btn-warning btn-sm">
                    <a href="{% url 'contacts:industry' %}" class="btn btn-secondary btn-sm">cancel</a>
                {% else %}
                    <input type="submit" value="create" class="ms-2 btn btn-erp-primary btn-sm">
                {% endif %}
            </form>
            <div class="px-4">
                {% for industries in industries.number %}
                    {{ industries }}
                {% endfor %}

                {{ page_industry.number }}-{{ page_industry.paginator.num_pages }}
                {% if page_industry.has_previous %}
                    <a href="?page={{ page_industry.previous_page_number }}"><i class="bi bi-caret-left-square-fill"></i></a>
                {% endif %}
                {% if page_industry.has_next %}
                    <a href="?page={{ page_industry.next_page_number }}"><i class="bi bi-caret-right-square-fill"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row p-4">
        <table class="table">
            <thead class="table-light">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% if page_industry %}
                {% for industry in page_industry %}
                    <tr>
                        <td>{{ industry.id }}</td>
                        <td>{{ industry.name }}</td>
                        <td>{{ industry.description }}</td>
                        <td><a href="{% url 'contacts:update-industry' industry.pk %}" class="btn btn-warning btn-sm"><i
                                class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'contacts:delete-industry' industry.pk %}" class="btn btn-danger btn-sm"><i
                                    class="bi bi-trash3"></i></a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>
                        No found data.
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>

    </div>
{% endblock %}

contacts/templates/suppliers.html
{% extends 'home.html' %}
{% block title %}
    Suppliers
{% endblock %}