accounting/urls.py
from django.urls import path
from .views import *

app_name = 'accounting'

urlpatterns = [
    path('chart-accounts/', chart_of_accounts, name="chart-accounts"),
    path('chart-accounts/update/<int:pk>', update_chart_of_accounts, name="update-chart-accounts"),
    path('chart-accounts/delete/<int:pk>', delete_chart_of_accounts, name="delete-chart-accounts"),
    path('chart-accounts/csv_export/', char_of_account_export, name='export-accounts'),
    path('chart-accounts/csv_import/', import_chart_of_account, name='import-accounts'),
    path('taxes/', home_taxes, name='taxes'),
    path('taxes/<int:pk>', update_taxes, name='updated-taxes'),
    path('taxes/delete/<int:pk>', delete_taxes, name='delete-taxes'),
    path('currency/', home_currency, name='currency'),
    path('currency/<int:pk>', update_currency, name='update-currency'),
    path('currency/delete/<int:pk>', delete_currency, name='delete-currency'),
    path('bank-account/', bank_account, name="bank-account"),
]

contacts/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('industry/', create_industry, name='industry'),
    path('industry/update/<int:pk>', update_industry, name='update-industry'),
    path('industry/delete/<int:pk>', delete_industry, name='delete-industry'),
    path('country/', home_countries, name='country'),
    path('country/update/<int:pk>', update_country, name='update-country'),
    path('country/delete/<int:pk>', delete_country, name='delete-country'),
    path('cities/', home_cities, name='cities'),
    path('cities/update/<int:pk>', update_cities, name='update-cities'),
    path('cities/delete/<int:pk>', delete_cities, name='delete-cities'),
    path('employees/', home_employees, name='employees'),
    path('customers/', home_customers, name='customers'),
    path('customers/new/', create_customers, name='create-customers'),
    path('customers/update/<int:pk>', update_customers, name='update-customers'),
    path('customers/delete/<int:pk>', delete_customers, name='delete-customers'),
    path('customers/export_csv/', export_customers, name='export-customers'),
    path('suppliers/', home_suppliers, name='suppliers'),
]

erpLite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('login.urls'), name='login'),
    path('', include('home.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name="home"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Home
@login_required(login_url='login')
def home(request):
    return render(request, 'dashboard/dashboard.html')

home/templates/header/navBar.html
{% load static %}
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'logo.png' %}" alt="" width="100">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home'%}">Dashboard</a>
                </li>
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Accounting
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <p class="ps-2 m-0 fw-bold text-muted">Transactions</p>
                        </li>
                        <li><a class="dropdown-item" href="">Journal Entries</a></li>
                        <li>
                            <hr class="dropdown-divider">
                            <p class="ps-2 m-0 fw-bold text-muted">Reporting</p>
                        </li>
                        <li><a class="dropdown-item" href="">Balance Sheet</a></li>
                        <li><a class="dropdown-item" href="">Profit and Loss</a></li>
                        <li><a class="dropdown-item" href="">Trial Balance</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Reporting
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <p class="ps-2 m-0 fw-bold text-muted">Statements Reports</p>
                        </li>
                        <li><a class="dropdown-item" href="">Balance Sheet</a></li>
                        <li><a class="dropdown-item" href="">Profit and Loss</a></li>
                        <li><a class="dropdown-item" href="">Trial Balance</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="">Report 4</a></li>
                        <li><a class="dropdown-item" href="">Report 5</a></li>
                        <li><a class="dropdown-item" href="">Report 6</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Contacts
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'contacts:customers' %}">Customers</a></li>
                        <li><a class="dropdown-item" href="{% url 'contacts:suppliers' %}">Suppliers</a></li>
                        <li><a class="dropdown-item" href="{% url 'contacts:employees' %}">Employees</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'contacts:industry' %}">Industries</a></li>
                        <li><a class="dropdown-item" href="{% url 'contacts:country' %}">Countries</a></li>
                        <li><a class="dropdown-item" href="{% url 'contacts:cities' %}">Cities</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Configuration
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'accounting:chart-accounts' %}">Chart of Accounts</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounting:taxes' %}">Taxes</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounting:currency' %}">Currencies</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounting:bank-account' %}">Bank Acccounts</a></li>
                    </ul>
                </li>
            </ul>
            <div class="d-flex justify-content-center align-items-center">
                {% if request.user.is_authenticated %}
                <p>Hello, {{ request.user.username }}</p>
                {% endif %}
                <a class="nav-link" href="{% url 'logout' %}">Logout
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-arrow-right-square" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                              d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm4.5 5.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                    </svg>
                </a>
            </div>
        </div>
    </div>
</nav>