accounting/urls.py
from django.urls import path
from .views import *

app_name = 'accounting'

urlpatterns = [
    path('chart-accounts/', chart_of_accounts, name="chart-accounts"),
    path('chart-accounts/update/<int:pk>', update_chart_of_accounts, name="update-chart-accounts"),
    path('chart-accounts/delete/<int:pk>', delete_chart_of_accounts, name="delete-chart-accounts"),
    path('chart-accounts/csv_export/', char_of_account_export, name='export-accounts'),
    path('chart-accounts/csv_import/', import_chart_of_account, name='import-accounts'),
    path('taxes/', home_taxes, name='taxes'),
    path('taxes/<int:pk>', update_taxes, name='updated-taxes'),
    path('taxes/delete/<int:pk>', delete_taxes, name='delete-taxes'),
    path('currency/', home_currency, name='currency'),
    path('currency/<int:pk>', update_currency, name='update-currency'),
    path('currency/delete/<int:pk>', delete_currency, name='delete-currency'),
    path('bank-account/', bank_account, name="bank-account"),
]

erpLite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('login.urls'), name='login'),
    path('', include('home.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('accounting/', include('accounting.urls', namespace='accounting')),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name="home"),
]

accounting/models.py
from django.db import models


# Category chart of accounts
class CategoryAccounts(models.Model):
    name = models.CharField(max_length=220)

    def __str__(self):
        return self.name


# Chart of Accounts
class ChartOfAccounts(models.Model):
    class Status(models.TextChoices):
        SAVED = 'SV', 'Saved'
        PUBLISHED = 'PB', 'Published'

    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=220)
    type = models.ForeignKey(CategoryAccounts, on_delete=models.CASCADE)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.SAVED)

    def __str__(self):
        return f'{self.code} {self.name}'

    class Meta:
        ordering = ['code']


# Taxes
class Taxes(models.Model):
    code = models.CharField(max_length=10)
    tax_name = models.CharField(max_length=220)
    account_id = models.ForeignKey(ChartOfAccounts, on_delete=models.CASCADE)
    percentage = models.IntegerField()


# Currency
class Currency(models.Model):
    name = models.CharField(max_length=220)
    symbol = models.CharField(max_length=5)
    abbrev = models.CharField(max_length=10)
    date = models.DateField()
    rate = models.DecimalField(max_digits=6, decimal_places=2)
    status = models.BooleanField()


# Journal Entryes
class JournalEntries(models.Model):
    date = models.DateField()
    account_id = models.ForeignKey(ChartOfAccounts, on_delete=models.CASCADE)
    reference = models.CharField(max_length=250)
    debit = models.DecimalField(max_digits=10, decimal_places=2)
    credit = models.DecimalField(max_digits=10, decimal_places=2)

accounting/forms.py
from django.forms import ModelForm
from django.forms.widgets import TextInput, DateTimeInput, NumberInput, CheckboxInput
from .models import ChartOfAccounts, Taxes, Currency


class FormChartOfAccounts(ModelForm):
    class Meta:
        model = ChartOfAccounts
        fields = '__all__'


class FormTaxes(ModelForm):
    class Meta:
        model = Taxes
        fields = '__all__'


class FormCurrency(ModelForm):

    class Meta:
        currency_field = "form-control"
        model = Currency
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={"class": f"{currency_field}"}),
            'abbrev': TextInput(attrs={"class": f"{currency_field}"}),
            'symbol': TextInput(attrs={"class": f"{currency_field}"}),
            'date': DateTimeInput(attrs={'type': 'date', "class": f"{currency_field}"}),
            'rate': NumberInput(attrs={"class": f"{currency_field}"}),
            'status': CheckboxInput(attrs={"type": "checkbox",
                                         "class": "form-check-input"}),
        }

accounting/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import ChartOfAccounts, Taxes, Currency, CategoryAccounts
from .forms import FormChartOfAccounts, FormTaxes, FormCurrency
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import csv
import os

# Home Chart of Accounts
@login_required(login_url='login')
def chart_of_accounts(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    account_filter = ChartOfAccounts.objects.filter(
        Q(name__icontains=q)
    )
    chartAccounts = ChartOfAccounts.objects.all()
    form = FormChartOfAccounts()
    if request.method == 'POST':
        form = FormChartOfAccounts(request.POST)
        if form.is_valid():
            form.save()
        return redirect('accounting:chart-accounts')
    # paginator = Paginator(ChartOfAccounts.objects.all(), 15)
    paginator = Paginator(account_filter, 15)
    page_number = request.GET.get('page')
    page_accounts = paginator.get_page(page_number)
    context = {
        'chartAccounts': chartAccounts,
        'form': form,
        'page_accounts': page_accounts,
        # 'account_filter': account_filter
    }
    return render(request, 'chartOfAccounts.html', context)


# Update Chart of Accounts
@login_required(login_url='login')
def update_chart_of_accounts(request, pk):
    chartAccounts = ChartOfAccounts.objects.get(id=pk)
    if request.method == 'POST':
        form = FormChartOfAccounts(request.POST,instance=chartAccounts)
        if form.is_valid():
            form.save()
        return redirect('accounting:chart-accounts')
    else:
        form = FormChartOfAccounts(instance=chartAccounts)
    chartAccounts = ChartOfAccounts.objects.all()
    page_name = request.path
    context = {
        'form': form,
        'page_name': page_name,
        'chartAccounts': chartAccounts,
    }
    return render(request, 'chartOfAccounts.html', context)

# Delete Char of Accounts
@login_required(login_url='login')
def delete_chart_of_accounts(request, pk):
    chartAccounts = ChartOfAccounts.objects.get(id=pk)
    chartAccounts.delete()
    return redirect('accounting:chart-accounts')

# Char of Account Import CSV
@login_required(login_url='login')
def import_chart_of_account(request):
    accounts = []
    with open("accounts.csv", "r") as csv_file:
        data = list(csv.reader(csv_file, delimiter=","))
        for row in data[1:]:
            accounts.append(
                ChartOfAccounts(
                    code=row[0],
                    name=row[1],
                    type=CategoryAccounts.objects.get(name=row[2])
                )
            )
    if len(accounts) > 0:
        ChartOfAccounts.objects.bulk_create(accounts)
    return HttpResponse("Succesfully Imported")


# Chart of Account Export CSV
@login_required(login_url='login')
def char_of_account_export(request):
    response = HttpResponse(content_type='type/csv')
    response['Content-Disposition'] = 'attachment; filename=accounts.csv'
    writer = csv.writer(response)
    accounts = ChartOfAccounts.objects.all()
    writer.writerow(['Code', 'Name', 'Type'])

    for account in accounts:
        writer.writerow(([account.code, account.name, account.type]))
    return response


# Taxes
@login_required(login_url='login')
def home_taxes(request):
    form = FormTaxes()
    if request.method == 'POST':
        form = FormTaxes(request.POST)
        if form.is_valid():
            form.save()
        return redirect('accounting:taxes')
    taxes = Taxes.objects.all()
    paginator = Paginator(Taxes.objects.all(), 6)
    page_number = request.GET.get('page')
    page_taxes = paginator.get_page(page_number)
    context = {
        'form': form,
        'taxes': form,
        'page_taxes': page_taxes,
    }
    return render(request,'taxes.html', context)


# Taxes Update
@login_required(login_url='page')
def update_taxes(request, pk):
    taxes = Taxes.objects.get(id=pk)
    if request.method == 'POST':
        form = FormTaxes(request.POST, instance=taxes)
        if form.is_valid():
            form.save()
        return redirect('accounting:taxes')
    else:
        form = FormTaxes(instance=taxes)
    page_taxes = Taxes.objects.all()
    page_name = request.path
    context = {
        'form': form,
        'page_taxes': page_taxes,
        'page_name': page_name
    }
    return render(request, 'taxes.html', context)


# Tax Delete
@login_required(login_url='page')
def delete_taxes(request, pk):
    taxes = Taxes.objects.get(id=pk)
    taxes.delete()
    return redirect(request, 'taxes.html')


# Currency
@login_required(login_url='page')
def home_currency(request):
    form = FormCurrency()
    if request.method == 'POST':
        form = FormCurrency(request.POST)
        if form.is_valid():
            form.save()
        return redirect('accounting:currency')
    currencies = Currency.objects.all()
    context = {
        'form': form,
        'currencies': currencies,
    }
    return render(request, 'currency.html', context)


# Update Currency
@login_required(login_url='login')
def update_currency(request, pk):
    obj = Currency.objects.get(id=pk)
    if request.method == 'POST':
        form = FormCurrency(request.POST, instance=obj)
        if form.is_valid():
            form.save()
        return redirect('accounting:currency')
    else:
        form = FormCurrency(instance=obj)
    context = {
        'form': form,
        'obj': obj
    }
    return render(request, 'updateCurrency.html', context)

# Delete Currencey
@login_required(login_url='login')
def delete_currency(request, pk):
    currency = Currency.objects.get(id=pk)
    currency.delete()
    return redirect('accounting:currency')

# Bank account
def bank_account(request):
    return render(request, 'bankAccount.html')

accounting/templates/bankAccount.html
{% extends 'home.html' %}
{% block title %}
Bank Account
{% endblock %}

accounting/templates/chartOfAccounts.html
{% extends 'home.html' %}
{% block title %}
Chart of Accounts
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row align-items-center mt-4 mb-4">
        <div class="col-md-8">
        <form method="POST" action="">
            {% csrf_token %}
            {{ form }}
            {# {% if request.method == 'POST' %}#}
            {% if page_name %}
            <input type="submit" value="update" class="ms-2 btn btn-warning btn-sm">
            <a href="{% url 'accounting:chart-accounts' %}" class="btn btn-secondary btn-sm">cancel</a>
            {% else %}
            <input type="submit" value="create" class="ms-2 btn btn-sm btn-erp-primary">
            {% endif %}
        </form>
    </div>
        <div class="col-md-4 d-flex justify-content-end">
        <div class="">
            <p>{{ page_accounts.number }}-{{ page_accounts.paginator.num_pages }}</p>
        </div>
        <div class="me-4">
            {% if page_accounts.has_previous %}
            <a class="paginator" href="?page={{ page_accounts.previous_page_number }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="20" fill="currentColor"
                     class="bi bi-caret-left-fill" viewBox="0 0 16 16">
                    <path d="m3.86 8.753 5.482 4.796c.646.566 1.658.106 1.658-.753V3.204a1 1 0 0 0-1.659-.753l-5.48 4.796a1 1 0 0 0 0 1.506z"/>
                </svg>
            </a>
            {% endif %}
            {% if page_accounts.has_next %}
            <a class="paginator" href="?page={{ page_accounts.next_page_number }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="20" fill="currentColor"
                     class="bi bi-caret-right-fill" viewBox="0 0 16 16">
                    <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                </svg>
            </a>
            {% endif %}
        </div>
        <div class="me-2">
            <a class="btn btn btn-outline-secondary btn-sm " href="{% url 'accounting:import-accounts' %}"><i
                    class="bi bi-save"></i><span class="ps-2">Import CSV</span></a>
        </div>
        <div>
            <a class="btn btn-secondary btn-sm " href="{% url 'accounting:export-accounts' %}"><i
                    class="bi bi-save"></i><span class="ps-2">Export CSV</span></a>
        </div>
    </div>
    <div class="col-md-3 mx-auto mt-4 d-flex justify-content-center">
        <form action="" method="GET" class="search-chart">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search"
                 viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
                <input type="search" name="q" placeholder="Search..." class="input-chart" value="{{ request.GET.q }}">
        </form>
    </div>
    </div>
    <div class="row bg-white p-4">
    <table class="table">
        <thead class="table-light">
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Type</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% if page_accounts %}
        {% for account in page_accounts %}
        <tr>
            <td>{{ account.code }}</td>
            <td>{{ account.name }}</td>
            <td>{{ account.type }}</td>
            <td>
                <div class="form-check form-switch">
                    <input
                            class="form-check-input"
                            type="checkbox"
                            role="switch"
                            id="flexSwitchCheckDefault"
                            {% if account.status == "PB" %} checked {% else %} {% endif %}
                    disabled>
                </div>
            <td><a href="{% url 'accounting:update-chart-accounts' account.pk %}"
                   class="btn btn-warning btn-sm">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd"
                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
            </a>
                <a href="{% url 'accounting:delete-chart-accounts' account.pk %}" class="btn btn-danger btn-sm">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-trash3-fill" viewBox="0 0 16 16">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                    </svg>
                </a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>
                No found data.
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

</div>
</div>
{% endblock %}

accounting/templates/currency.html
{% extends 'home.html' %}
{% block title %}
Currencies
{% endblock %}
{% block content %}
<div class="row py-4">
    <div class="d-flex justify-content-between">
        <button type="button" class="btn btn-erp-primary btn-sm" data-bs-toggle="modal" data-bs-target="#ModalCurrency">
            Add Currency
        </button>
        <div class="px-4">
            {{ page_accounts.number }}-{{ page_accounts.paginator.num_pages }}
            {% if page_accounts.has_previous %}
            <a href="?page={{ page_accounts.previous_page_number }}"><i
                    class="bi bi-caret-left-square-fill"></i></a>
            {% endif %}
            {% if page_accounts.has_next %}
            <a href="?page={{ page_accounts.next_page_number }}"><i
                    class="bi bi-caret-right-square-fill"></i></a>
            {% endif %}
        </div>
    </div>
</div>
<div class="row bg-white">
    <table class="table">
        <thead class="table-light">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Currency</th>
            <th>Symbol</th>
            <th>Date</th>
            <th>Rate</th>
            <th>Active</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% if currencies %}
        {% for currency in currencies %}
        <tr>
            <td>{{ currency.id }}</td>
            <td>{{ currency.name }}</td>
            <td>{{ currency.abbrev }}</td>
            <td>{{ currency.symbol }}</td>
            <td>{{ currency.date|date:"d/m/Y" }}</td>
            <td>{{ currency.rate }}</td>
            <td>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked"
                           {% if currency.status %}checked{% else %}{% endif %}>
                </div>
            <td>
                <button onclick="update_currency('{% url 'accounting:update-currency' currency.pk %}')"
                        class="btn btn-warning btn-sm">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd"
                              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                </button>
                <a href="{% url 'accounting:delete-currency' currency.pk %}"
                   class="btn btn-danger btn-sm">

                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-trash3-fill" viewBox="0 0 16 16">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                    </svg>
                </a></td>
        </tr>

        {% endfor %}
        {% else %}
        <tr>
            <td>
                No found data.
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- Modal -->
    <div class="modal fade" id="ModalCurrency" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create Currency</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="POST">
                    <input type="hidden" value="{{ obj.id }}">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="container-fluid">
                            <div class="row mb-3">
                                <div class="col-12">
                                    <label for="" class="form-label">Name</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-4">
                                    <label for="" class="form-label">Currency</label>
                                    {{ form.abbrev }}
                                </div>
                                <div class="col-2">
                                    <label for="" class="form-label">Symbol</label>
                                    {{ form.symbol }}
                                </div>
                                <div class="col-6">
                                    <label for="" class="form-label">Date</label>
                                    {{ form.date }}
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-4">
                                    <label for="" class="form-label">Rate</label>
                                    {{ form.rate }}
                                </div>
                                <div class="align-self-end col-4 ms-auto">
                                    <div class="form-check form-switch ">
                                        {{ form.status }}
                                        <label class="form-check-label" for="flexSwitchCheckChecked">Active</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="edicion">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block CustomScripts %}
<script type="text/javascript">
        function update_currency(url){
            {#$('#edicion').load(url, function (){#}
            {#    $(this).modal('show')#}
           $('#edicion').load(url, function (){
                $(this).modal('show')
           })

            {#var myModal = new bootstrap.Modal(document.getElementById('UpdateModalCurrency'),)#}
            {#myModal.show()#}

        }

</script>
{% endblock %}

accounting/templates/taxes.html
{% extends 'home.html' %}
{% block title %}
    Taxes
{% endblock %}
{% block content %}
    <div class="row py-4">
        <div class="d-flex justify-content-between">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form }}
{#                {% if request.method == 'POST' %}#}
                {% if page_name %}
                    <input type="submit" value="update" class="ms-2 btn btn-warning btn-sm">
                    <a href="{% url 'accounting:taxes' %}" class="btn btn-secondary btn-sm">cancel</a>
                {% else %}
                    <input type="submit" value="create" class="ms-2 btn btn-erp-primary btn-sm">
                {% endif %}
            </form>
            <div class="px-4">
                {{ page_accounts.number }}-{{ page_accounts.paginator.num_pages }}
                {% if page_accounts.has_previous %}
                    <a href="?page={{ page_accounts.previous_page_number }}"><i class="bi bi-caret-left-square-fill"></i></a>
                {% endif %}
                {% if page_accounts.has_next %}
                    <a href="?page={{ page_accounts.next_page_number }}"><i class="bi bi-caret-right-square-fill"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row bg-white p-4">
        <table class="table">
            <thead class="table-light">
            <tr>
                <th>ID</th>
                <th>Code</th>
                <th>Tax Name</th>
                <th>Account</th>
                <th>Percentage</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% if page_taxes %}
                {% for tax in page_taxes %}
                    <tr>
                        <td>{{ tax.id }}</td>
                        <td>{{ tax.code }}</td>
                        <td>{{ tax.tax_name }}</td>
                        <td>{{ tax.account_id }}</td>
                        <td>{{ tax.percentage }}%</td>
                        <td><a href="{% url 'accounting:updated-taxes' tax.pk %}" class="btn btn-warning btn-sm"><i
                                class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'accounting:delete-taxes' tax.pk %}" class="btn btn-danger btn-sm"><i
                                    class="bi bi-trash3"></i></a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>
                        No found data.
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>

    </div>
{% endblock %}

accounting/templates/updateCurrency.html
<!-- Modal -->
<div class="modal fade" id="UpdateModalCurrency" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Update Currency</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="container-fluid">
                        <div class="row mb-3">
                            <div class="col-12">
                                <label for="" class="form-label">Name</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-4">
                                <label for="" class="form-label">Currency</label>
                                {{ form.abbrev }}
                            </div>
                            <div class="col-2">
                                <label for="" class="form-label">Symbol</label>
                                {{ form.symbol }}
                            </div>
                            <div class="col-6">
                                <label for="" class="form-label">Date</label>
                                {{ form.date }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-4">
                                <label for="" class="form-label">Rate</label>
                                {{ form.rate }}
                            </div>
                            <div class="align-self-end col-4 ms-auto">
                                <div class="form-check form-switch ">
                                    {{ form.status }}
                                    <label class="form-check-label" for="flexSwitchCheckChecked">Active</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save">
                </div>
            </form>
        </div>
    </div>
</div>